name = "ecom-insight-hub"
compatibility_date = "2024-01-22"
pages_build_output_dir = "dist/public"

[vars]
VITE_STRIPE_PUBLISHABLE_KEY = "pk_test_51SmUtnHL8Re8eVeSvI60MBhhzJ2PXlaGZoR3sDfSkpwDf9ulQ8cLcDIn5LhTfVDE2KDhRqN9cHovcdWCGLL7wXNf00aLZnJyEL"
# STRIPE_SECRET_KEY must be added in Cloudflare Dashboard -> Settings -> Variables
# NODE_ENV = "production" # Optional
[[d1_databases]]
binding = "DB"
database_name = "ecom-db"
database_id = "459fc68b-5813-4deb-9f7e-b4db5fc16cc0"

